thislist = ["caleb", "Mayaka", "Ombogo"]
print(thislist)
print(type(thislist))
print(thislist[0:2])
print(len(thislist))
thislist.append("2023")
print(thislist)
thislist.remove("caleb")
print(thislist)

thislist2 = list(("python", "django", "C++", "python"))
print(thislist2)
thislist2.append("javascript")
print(thislist2)
print(len(thislist2))
#thislist2.clear()
print(thislist2)
thislist2.append("langauge 1")
print(thislist2)
print(thislist.index("Mayaka"))
print(thislist2.count("python"))